import type {
  AppraisalDetail,
  AppraisalRevision,
  AppraisalTemplate,
  AppraisalTemplateCategory,
} from "@/types/appraisals"

/**
 * A template shaped like the scope's own: seven weighted performance areas
 * spread across the three lenses, totalling 100%.
 */
export const SEVEN_AREAS: AppraisalTemplateCategory[] = [
  { name: "Technical Skills & Code Quality", lens: "past", weight: 20 },
  { name: "Delivery & Productivity", lens: "past", weight: 20 },
  { name: "Ownership & Accountability", lens: "past", weight: 15 },
  { name: "AI & Modern Engineering Skills", lens: "future_readiness", weight: 15 },
  { name: "Learning & Skill Growth", lens: "current_capability", weight: 10 },
  { name: "Communication & Teamwork", lens: "current_capability", weight: 10 },
  { name: "Business & Client Impact", lens: "past", weight: 10 },
].map((category, index) => ({
  id: `cat-${index + 1}`,
  name: category.name,
  description: null,
  lens: category.lens as AppraisalTemplateCategory["lens"],
  weight: category.weight,
  position: index,
  questions: [
    {
      id: `q-${index + 1}`,
      prompt: `How did you do on ${category.name}?`,
      description: null,
      position: 0,
      selfRating: true,
      managerRating: true,
      requiresComment: false,
      required: true,
    },
  ],
}))

export const template: AppraisalTemplate = {
  id: "tpl-1",
  name: "FY26 Performance Review",
  description: null,
  status: "active",
  version: 1,
  lineageId: "tpl-1",
  inUse: true,
  totalWeight: 100,
  categories: SEVEN_AREAS,
  createdAt: "2026-01-01T09:00:00Z",
}

export function revision(overrides: Partial<AppraisalRevision> & { id: string }): AppraisalRevision {
  return {
    versionNumber: 1,
    label: "V1",
    stage: "self_appraisal",
    submittedAt: "2026-02-01T09:00:00Z",
    calculatedScore: null,
    authorName: null,
    summary: null,
    achievements: null,
    strengths: null,
    improvementAreas: null,
    trainingNeeds: null,
    nextPeriodGoals: null,
    answers: [],
    ...overrides,
  }
}

export function appraisal(overrides: Partial<AppraisalDetail> = {}): AppraisalDetail {
  return {
    id: "app-1",
    status: "self_appraisal_open",
    appraisalCycleId: "cyc-1",
    employeeId: "emp-1",
    employee: null,
    cycleName: "FY26 Review",
    employeeName: "Sofia Reyes",
    employeeCode: "ACM-004",
    calculatedScore: null,
    finalScore: null,
    effectiveScore: null,
    releasedAt: null,
    acknowledgedAt: null,
    secondaryReviewApplicable: false,
    primaryManagerName: "Pat Primary",
    finalManagerName: "Fin Final",
    currentVersion: null,
    cycle: {
      id: "cyc-1",
      name: "FY26 Review",
      description: null,
      status: "active",
      assessmentPeriodStart: null,
      assessmentPeriodEnd: null,
      startsOn: null,
      employeeSubmissionDeadline: null,
      primaryReviewDeadline: null,
      secondaryReviewDeadline: null,
      finalizationDeadline: null,
      compensationEffectiveDate: null,
      secondaryReviewEnabled: false,
      reviewType: "annual",
      appraisalTemplateId: "tpl-1",
      templateName: "FY26 Performance Review",
      templateVersion: 1,
      started: true,
      startedAt: "2026-01-15T09:00:00Z",
      closedAt: null,
      eligibleCount: 1,
      appraisalCount: 1,
      statusCounts: {},
      createdAt: "2026-01-01T09:00:00Z",
    },
    template,
    revisions: [],
    comments: [],
    transitions: [],
    scoreOverrides: [],
    compensation: null,
    designationOptions: [],
    managers: { primary: null, secondary: null, final: null },
    selfAppraisalDraft: null,
    viewer: {
      level: null,
      isSubject: true,
      isAdministrator: false,
      canSaveSelfDraft: true,
      canSubmitSelf: true,
      canSubmitReview: false,
      canReturnForCorrection: false,
      canAdvance: false,
      canOverrideScore: false,
      canRelease: false,
      canAcknowledge: false,
      canManageCompensation: false,
      canSetManagementOnlyComment: false,
      visibleRevisionStages: ["self_appraisal"],
    },
    ...overrides,
  }
}
